app/views.py
import os.path

import flask
import base64
from flask import Blueprint,render_template, request, url_for, redirect
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash
from .menu import menu
from .models import Recipe, User, Category, recipe_category
from . import db


mainBlueprint = Blueprint('main', __name__)


def convert_image(image):
    img = image.read()
    if img == b'':
        def_image_path = 'app/static/images/new_recipe/default.jpg'
        with open(def_image_path, 'rb') as def_image:
            def_img = def_image.read()
            base64_data = base64.b64encode(def_img).decode('utf-8')
        return base64_data
    else:
        base64_data = base64.b64encode(img).decode('utf-8')
        return base64_data

def add_recipe_category(recipe, categories):
    for category in categories:
        cat = Category.query.get(category)
        recipe.categories.append(cat)

def select_status(button):
    if button == 'Drafts':
        status = 'Drafts'

    elif button == 'need-submit':
        status = 'need-submit'

    elif button == 'Delete':
        status = 'Delete'

    else:status = 'default'

    return status

def send_feedback(status):
    if status == 'Drafts':
        return flask.flash("Recipe in your drafts!", category="success")
    elif status == 'need-submit':
        return flask.flash("Recipe sent for submission!", category="success")
    elif status == 'Delete':
        return flask.flash("Recipe deleted!", category='success')
    else:
        return flask.flash("Occur some error. Try again", category="error")


#main
@mainBlueprint.route("/", methods=["GET", ' POST'])
@login_required
def home():
    recipes = Recipe.query.filter_by(status='Published').order_by(Recipe.id.desc()).limit(6).all()
    return render_template('home.html', menu=menu(), user=current_user, recipes=recipes)


@mainBlueprint.route("/categories", methods=["GET", ' POST'])
@login_required
def categories():
    all_categories = Category.query.all()
    return render_template('categories.html', menu=menu(), user=current_user, categories=all_categories)


@mainBlueprint.route("/categories/<string:name>", methods=["GET", ' POST'])
@login_required
def category(name):
    target_category = Category.query.filter_by(name=name).first()
    all_recipes = db.session.query(Recipe).join(recipe_category).filter(recipe_category.c.category_id == target_category.id).filter(Recipe.status == "Published").all()
    return render_template('special_category.html', menu=menu(), user=current_user, recipes=all_recipes)



@mainBlueprint.route('/new-recipe', methods=["POST", 'GET'])
@login_required
def new_recipe():
    categories_all = Category.query.all()

    if request.method == "POST":
        dish_name = request.form['dish_name']
        cooking_time = request.form['cooking_time']
        description = request.form['description']
        ingredients = request.form['ingredients']
        image = request.files['photo']
        selected_categories = request.form.getlist('checkbox')
        button = request.form['button']

        if dish_name != '':
            if selected_categories:
                new_rec = Recipe(
                    dish_name=dish_name,
                    cooking_time=cooking_time,
                    description=description,
                    ingredients=ingredients,
                    image=convert_image(image),
                    status=select_status(button),
                    user_id=current_user.id)

                add_recipe_category(new_rec, selected_categories)

                db.session.add(new_rec)
                db.session.commit()

                send_feedback(new_rec.status)

            else: flask.flash("Please select category.", category='error')
        else: flask.flash("Enter a dish name", category='error')

    return render_template('new-recipe.html', menu=menu(), user=current_user, categories=categories_all)


@mainBlueprint.route('/my-drafts', methods=["POST", 'GET'])
@login_required
def draft_recipes():
    if request.form:
        id = request.form['id']
        return redirect(url_for('main.update_draft', recipe_id=id))

    recipes = Recipe.query.filter_by(status='Drafts', user_id=current_user.id).all()
    return render_template('my-drafts.html', menu=menu(), user=current_user, recipes=recipes)


@mainBlueprint.route('/my-drafts/<int:recipe_id>', methods=["POST", 'GET'])
@login_required
def update_draft(recipe_id):
    recipe = Recipe.query.filter_by(id=recipe_id).first()
    selected_categories = recipe.categories
    categories = Category.query.all()

    if request.method == 'POST':
        recipe.dish_name = request.form['dish_name']
        recipe.cooking_time = request.form['cooking_time']
        recipe.description = request.form['description']
        recipe.ingredients = request.form['ingredients']
        image = request.files['photo']
        new_selected_categories = request.form.getlist('checkbox')
        button = request.form['button']

        if image.filename != "":
            recipe.image = convert_image(image)
            print("Photo updated")

        if new_selected_categories:
            recipe.categories.clear()
            add_recipe_category(recipe, new_selected_categories)

            if button == 'Delete':
                db.session.delete(recipe)
            else:
                recipe.status = select_status(button)

            db.session.commit()
            send_feedback(button)
            return redirect(url_for('main.draft_recipes'))

        else: flask.flash("Please select category.", category='error')


    return render_template('my-drafts-edit.html',menu=menu(), user=current_user, recipe=recipe, id=recipe.id,
                           categories=categories, selected_categories=selected_categories)


@mainBlueprint.route('/all-recipes', methods=["POST", 'GET'])
@login_required
def all_recipes():
    recipes = Recipe.query.filter_by(status='Published').all()
    return render_template('all-recipes.html', menu=menu(), user=current_user, recipes=recipes)


@mainBlueprint.route('/recipe/<int:id>', methods=["POST", 'GET'])
@login_required
def recipe(id):
    recipe = Recipe.query.filter_by(id=id).first()
    return render_template('recipe.html', menu=menu(), user=current_user, recipe=recipe)

@mainBlueprint.route('/profile', methods=["POST", 'GET'])
@login_required
def profile():
    user = User.query.filter_by(id=current_user.id).first()
    if request.method == 'POST':
        user.firstname = request.form.get('firstname')
        user.lastname = request.form.get('lastname')
        user.email = request.form.get('email')
        user.phone = request.form.get('phone')
        new_password = request.form.get('password')
        if new_password:
            user.password = generate_password_hash(new_password, method='scrypt')
        db.session.commit()
        flask.flash('Information updated!', category='success')
    return render_template('profile.html', menu=menu(), user=current_user)

app/templates/admin.html
{% extends 'base.html' %}

{% block content %}
<div class="page__admin">
    <div class="admin__sidebar sidebar">
        <ul class="sidebar__list">
            <li class="sidebar__item"><a href="{{ url_for('admin.dashboard_users') }}">Users</a></li>
            {% if user.role == 'admin' %}
            <li class="sidebar__item"><a href="{{ url_for('admin.dashboard_user_role') }}">Change user's role</a></li>
            {% endif %}
            <li class="sidebar__item"><a href="{{ url_for('admin.dashboard_recipes') }}">Recipes</a></li>
            <li class="sidebar__item"><a href="{{ url_for('admin.dashboard_categories') }}">Manage categories</a></li>
            <li class="sidebar__item"><a href="{{ url_for('admin.dashboard_recipes_for_submit') }}">Recipes for submit</a></li>

        </ul>
    </div>

    <div class="admin__content content">
        {% block admin_content %}
        <div class="content__cards">
            <div class="content__card">
                <h2>Total Users</h2>
                <div class="card__number">{{ total_users }}</div>
            </div>
            <div class="content__card">
                <h2>Total Recipes</h2>
                <div class="card__number">{{ total_recipes }}</div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

{% endblock %}








app/templates/admin_manage_categories.html
{% extends 'admin.html' %}

{% block admin_content %}
<div class="formbold-main-wrapper">
  <!-- Author: FormBold Team -->
  <!-- Learn More: https://formbold.com -->
  <div class="formbold-form-wrapper">

<!--    <img src="your-image-url-here.jpg">-->

    <form action="{{url_for('admin.dashboard_categories')}}" method="post" enctype="multipart/form-data">
      <div class="formbold-form-title">
        <h2 class="a">New category:</h2>
      </div>

      <div class="formbold-input-flex">
        <div>
          <label for="category_name" class="formbold-form-label">Category Name</label>
          <input type="text" name="category_name" id="category_name" class="formbold-form-input"/>
        </div>
          <div class="photos">
            <img src="/static/images/new_recipe/01.svg" alt="add photo">
            <label for="photo">Select image</label>
            <input type="file" name="photo" id="photo" accept=".jpeg, .png, .jpg">
        </div>
      </div>


        <button type="submit" class="formbold-btn" name="add_category" value="1">Add</button>

    </form>
    <form action="{{url_for('admin.dashboard_categories')}}" method="post">
        <div class="content__table table">
            <h1 class="table__title">All categories</h1>
            <div class="table__body">
                <ul class="table__list list-table">
                    <li class="list-table__items title">
                        <div class="table__item title">id</div>
                        <div class="table__item title">Category</div>
                        <div class="table__item title"></div>
                    </li>
                    {% for category in categories %}
                    <li class="list-table__items">
                        <div class="table__item">{{category.id}}</div>
                        {% if rename_button %}
                        {% if category.id == rename_id %}
                       <form action="{{url_for('admin.dashboard_categories')}}" method="get">
                           <input type="text" class="table__item" name="input_rename" value="{{category.name}}">
                           <button type="submit" class="table__item" name="submit_rename" value="submit_rename">Submit</button>
                       </form>
                        {% endif %}
                        {% else %}
                        <div class="table__item">{{category.name}}</div>

                        {% endif %}
                        <div class="item-table__form">
                            <form action="{{url_for('admin.dashboard_categories_all')}}" method="post" class="item-table__form">
                                <button type="submit" class="table__item item-table_button" name="rename" value="{{category.id}}">Rename</button>
                                <button type="submit" class="table__item item-table_button_secondary" name="delete" value="{{category.id}}">Delete</button>
                            </form>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </form>
  </div>
</div>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  body {
  }
  .formbold-mb-3 {
    margin-bottom: 15px;
  }
  .formbold-relative {
    position: relative;
  }
  .formbold-opacity-0 {
    opacity: 0;
  }
  .formbold-stroke-current {
    stroke: currentColor;
  }
  #supportCheckbox:checked ~ div span {
    opacity: 1;
  }

  .formbold-main-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .formbold-form-wrapper {
    margin: 0 auto;
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 40px;
  }
    .formbold-form-wrapper form {
    margin-top: 0px;
  }

  .formbold-img {
    margin-bottom: 45px;
  }

  .formbold-form-title {
    margin-bottom: 8px;
  }
  .formbold-form-title h2 {
    font-weight: 600;
    font-size: 28px;
    line-height: 34px;
    color: #07074d;
  }
  .formbold-form-title p {
    font-size: 16px;
    line-height: 24px;
    color: #536387;
    margin-top: 12px;
  }

  .formbold-input-flex {
    display: flex;
    gap: 20px;
    margin-bottom: 15px;
    align-items: end;
  }
  .formbold-input-flex > div {
    width: 40%;
  }
  .formbold-form-input {
    text-align: left;
    width: 100%;
    padding: 12px 16px;
    border-radius: 5px;
    border: 1px solid #dde3ec;
    background: #ffffff;
    font-weight: 500;
    font-size: 16px;
    color: #536387;
    outline: none;
    resize: none;
  }
  .formbold-form-input:focus {
    border-color: #6a64f1;
    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
  }
  .formbold-form-label {
    color: #536387;
    font-size: 14px;
    line-height: 24px;
    display: block;
    margin-bottom: 10px;
  }

  .formbold-checkbox-label {
    display: flex;
    cursor: pointer;
    user-select: none;
    font-size: 16px;
    line-height: 24px;
    color: #536387;
  }
  .formbold-checkbox-label a {
    margin-left: 5px;
    color: #6a64f1;
  }
  .formbold-input-checkbox {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
  }
  .formbold-checkbox-inner {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 20px;
    margin-right: 16px;
    margin-top: 2px;
    border: 0.7px solid #dde3ec;
    border-radius: 3px;
  }

  .photos {
    display: flex;
    flex-direction: row;
    gap: 10px;

    justify-content: center;
    align-items: center;
  }
.photos input {
  padding: 10px;
  }

  .formbold-btn {
    font-size: 16px;
    border-radius: 5px;
    padding: 14px 25px;
    border: none;
    font-weight: 500;
    background-color: #6a64f1;
    color: white;
    cursor: pointer;
    margin-top: 32px;
    width: 30%;
  }
  .drafts {
    background-color: #BDC5CC;
  }
  .formbold-btn:hover {
    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
  }

  .item-table__form{
    display: flex;
    justify-content: flex-end;
    flex-direction: row;
  }

.table__item{
    display: flex;
    align-items: center;
    }

</style>

{% endblock %}

app/templates/admin_new_role.html
{% extends 'admin.html' %}

{% block admin_content %}
<div class="formbold-main-wrapper">
  <!-- Author: FormBold Team -->
  <!-- Learn More: https://formbold.com -->
  <div class="formbold-form-wrapper">

<!--    <img src="your-image-url-here.jpg">-->

    <form action="{{url_for('admin.dashboard_user_role')}}" method="post">
      <div class="formbold-form-title">
        <h2 class="a">New role</h2>
        <p>Here you can change user's role.</p>
      </div>

      <div class="formbold-input-flex">
        <div>
          <label for="user_id" class="formbold-form-label">User_id</label>
          <input type="text" name="user_id" id="user_id" class="formbold-form-input"/>
        </div>
        <div>
          <label for="user_role" class="formbold-form-label"> User role </label>
          <select class="formbold-form-input" name="user_role" id="user_role">
            <option value="user">User</option>
            <option value="moderator">Moderator</option>
            <option value="admin">Admin</option>
          </select>
        </div>
      </div>

      <button type="submit" class="formbold-btn" name="button">Submit</button>
    </form>
  </div>
</div>
<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  body {
  }
  .formbold-mb-3 {
    margin-bottom: 15px;
  }
  .formbold-relative {
    position: relative;
  }
  .formbold-opacity-0 {
    opacity: 0;
  }
  .formbold-stroke-current {
    stroke: currentColor;
  }
  #supportCheckbox:checked ~ div span {
    opacity: 1;
  }

  .formbold-main-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .formbold-form-wrapper {
    margin: 0 auto;
    width: 100%;
  }

  .formbold-img {
    margin-bottom: 45px;
  }

  .formbold-form-title {
    margin-bottom: 30px;
  }
  .formbold-form-title h2 {
    font-weight: 600;
    font-size: 28px;
    line-height: 34px;
    color: #07074d;
  }
  .formbold-form-title p {
    font-size: 16px;
    line-height: 24px;
    color: #536387;
    margin-top: 12px;
  }

  .formbold-input-flex {
    display: flex;
    gap: 20px;
    margin-bottom: 15px;
  }
  .formbold-input-flex > div {
    width: 20%;
  }
  .formbold-form-input {
    text-align: left;
    width: 100%;
    padding: 12px 16px;
    border-radius: 5px;
    border: 1px solid #dde3ec;
    background: #ffffff;
    font-weight: 500;
    font-size: 16px;
    color: #536387;
    outline: none;
    resize: none;
  }
  .formbold-form-input:focus {
    border-color: #6a64f1;
    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
  }
  .formbold-form-label {
    color: #536387;
    font-size: 14px;
    line-height: 24px;
    display: block;
    margin-bottom: 10px;
  }

  .formbold-checkbox-label {
    display: flex;
    cursor: pointer;
    user-select: none;
    font-size: 16px;
    line-height: 24px;
    color: #536387;
  }
  .formbold-checkbox-label a {
    margin-left: 5px;
    color: #6a64f1;
  }
  .formbold-input-checkbox {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border-width: 0;
  }
  .formbold-checkbox-inner {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 20px;
    margin-right: 16px;
    margin-top: 2px;
    border: 0.7px solid #dde3ec;
    border-radius: 3px;
  }

  .photos {
    margin: 0 auto;
    border: 1px dashed var(--text, #3C322E);
    display: flex;
    flex-direction: column;
    gap: 10px;
    width: 275px;
    padding: 20px 20px;
    justify-content: center;
    align-items: center;
  }
.photos input {
  padding: 10px;
  }

  .formbold-btn {
    font-size: 16px;
    border-radius: 5px;
    padding: 14px 25px;
    border: none;
    font-weight: 500;
    background-color: #6a64f1;
    color: white;
    cursor: pointer;
    margin-top: 25px;
  }
  .drafts {
    background-color: #BDC5CC;
  }
  .formbold-btn:hover {
    box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
  }
</style>

{% endblock %}

app/templates/admin_recipes.html
{% extends 'admin.html' %}

{% block admin_content %}
<div class="content__table table">
    <h1 class="table__title">Recipes</h1>
    <div class="table__body">
        <ul class="table__list list-table">
            <ul class="list-table__items title">id
                <li class="table__item title">status</li>
                <li class="table__item title">user_id</li>
                <li class="table__item title">dish_name</li>
                <li class="table__item title">cooking_time</li>
            </ul>
            {% for recipe in recipes %}
            <ul class="list-table__items">{{recipe.id}}
                <li class="table__item">{{recipe.status}}</li>
                <li class="table__item">{{recipe.user_id}}</li>
                <li class="table__item">{{recipe.dish_name}}</li>
                <li class="table__item">{{recipe.cooking_time}}</li>
            </ul>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}










app/templates/admin_recipes_for_submit.html
{% extends 'admin.html' %}

{% block admin_content %}
<div class="content__table table">
    <h1 class="table__title">Recipes for submit</h1>
    <div class="table__body">
        <ul class="table__list list-table">
            <li class="list-table__items title">id
                <div class="table__item title">status</div>
                <div class="table__item title">user_id</div>
                <div class="table__item title">dish_name</div>
                <div class="table__item title">cooking_time</div>
                <div class="table__item title">description</div>
                <div class="table__item title">ingredients</div>
                <div class="table__item title"></div>
            </li>
            {% for recipe in recipes %}
            <li class="list-table__items">{{recipe.id}}
                <div class="table__item">{{recipe.status}}</div>
                <div class="table__item">{{recipe.user_id}}</div>
                <div class="table__item">{{recipe.dish_name}}</div>
                <div class="table__item">{{recipe.cooking_time}}</div>
                <div class="table__item">{{recipe.description}}</div>
                <div class="table__item">{{recipe.ingredients}}</div>
                <form action="{{url_for('admin.dashboard_recipes_for_submit')}}" method="post" class="item-table__form">
                    <button type="submit" class="table__item item-table_button" name="publish" value="{{recipe.id}}">Publish</button>
                    <button type="submit" class="table__item item-table_button_secondary" name="return" value="{{recipe.id}}">Return</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}










app/templates/admin_users.html
{% extends 'admin.html' %}

{% block admin_content %}
<div class="content__table table">
    <h1 class="table__title">Users</h1>
    <div class="table__body">
        <ul class="table__list list-table">
            <ul class="list-table__items title">id
                <li class="table__item title">email</li>
                <li class="table__item title">role</li>
                <li class="table__item title">firstname</li>
                <li class="table__item title">lastname</li>
                <li class="table__item title">phone</li>
                <li class="table__item title">Recipes</li>
            </ul>
            {% for user in users %}
            <ul class="list-table__items">{{user.id}}
                <li class="table__item">{{user.email}}</li>
                <li class="table__item">{{user.role}}</li>
                <li class="table__item">{{user.firstname}}</li>
                <li class="table__item">{{user.lastname}}</li>
                <li class="table__item">{{user.phone}}</li>
                <li class="table__item">{{user.recipes|length}}</li>
            </ul>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}










app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../static/css/style.css">
    <title>FoodClub</title>
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <div class="header__container">
                <div class="header__body">
                    <a href="{{url_for('main.home')}}" class="header__logo">
                    Food Club
                    </a>
                    <nav class="header__menu menu">
                    <div class="menu__body">
                        <ul class="menu__list">
                            {% for key, value in menu.items() %}
                            {% if user.is_authenticated %}
                            {% if key != 'Sign In' and key != 'Sign Up' %}
                            <li class="menu__item">
                                <a href="{{ value }}" class="menu__link">{{ key }}</a>
                            </li>
                            {% endif %}
                            {% else %}
                            {% if key == 'Sign In' or key == 'Sign Up' %}
                            <li class="menu__item">
                                <a href="{{ value }}" class="menu__link">{{ key }}</a>
                            </li>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                            {% if user.role == 'admin' or user.role == 'moderator' %}
                            <li class="menu__item">
                                <a href="{{ url_for('admin.dashboard') }}" class="menu__link">Admin panel</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                    </nav>
                </div>
            </div>
        </header>
        <main class="page">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            {% if category == "success" %}
            <div class="page__flashes flash success" role="alert">
                <p class="flash__text">{{ message }}</p>
                <!--  <button type="button" class="close" data-dismiss="alert">
                     <span aria-hidden="true">&times;</span>
                </button> -->
            </div>
            {% else %}
            <div class="page__flashes flash error">
                <p class="flash__text">{{ message }}</p>
               <!-- <button type="button" class="close" data-dismiss="alert">
                     <span aria-hidden="true">&times;</span>
                </button> -->
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="page__container">
                 <h5 class="hello">User {{user.firstname}}</h5>
                {% block content %}

                {% endblock %}
            </div>
        </main>
        <footer class="footer">
            <div class="footer__container">
               <div class="footer__body">
                    <div class="footer__content content-footer">
                        <a href="/" class="content-footer__title">Food Club</a>
                        <div class="content-footer__text">
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint optio inventore blanditiis vel quos sit quis eligendi recusandae reprehenderit ipsam sunt excepturi, ea odit id repudiandae ab nulla sequi tempore?
                            </p>
                        </div>
                    </div>
                    <div class="footer__menu menu-footer">
                        <div class="menu-footer__item">
                        <div class="menu-footer__title">Menu</div>
                        <ul class="menu-footer__list list-menu-footer">
                            {% for key, value in menu.items() %}
                            {% if user.is_authenticated %}
                            {% if key != 'Sign In' and key != 'Sign Up' %}
                            <li class="list-menu-footer__item">
                                <a href="{{ value }}" class="list-menu-footer__link">{{ key }}</a>
                            </li>
                            {% endif %}
                            {% else %}
                            {% if key == 'Sign In' or key == 'Sign Up' %}
                            <li class="list-menu-footer__item">
                                <a href="{{ value }}" class="list-menu-footer__link">{{ key }}</a>
                            </li>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                    </div>
                    <ul class="menu-footer__social social-menu-footer">
                            <li class="social-menu-footer__item">
                                <img src="../static/images/01.svg" alt="social">
                            </li>
                            <li class="social-menu-footer__item">
                                <img src="../static/images/02.svg" alt="social">
                            </li>
                            <li class="social-menu-footer__item">
                                <img src="../static/images/03.svg" alt="social">
                            </li>
                            <li class="social-menu-footer__item">
                                <img src="../static/images/04.svg" alt="social">
                            </li>
                    </ul>
                </div>
               </div> 
               <div class="footer__copy">©2023 Petrovych</div>
        </footer>
    </div>
</body>
</html>

app/templates/categories.html
{% extends 'base.html' %}

{% block content %}
<div class="page__recent">
  <div class="page__title"><h1>All categories</h1></div>
  <div class="page__cards">
  {% for category in categories %}
  <div class="page__card card card_category">
  <div class="card_category__image">
    <img src="data:image/jpeg;base64,{{ category.image }}" alt="image">
  </div>
      <div class="body-card__title body-card__title_category">
        <a href="{{ url_for('main.category', name = category.name)}}" class="body-card__link body-card__link_category">{{ category.name }}</a>

      </div>
  </div>
  {% endfor %}
</div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="page__recent">
  <div class="page__title"><h1>Recent recipes</h1></div>
  <div class="page__cards">
  {% for recipe in recipes %}
  <div class="page__card card">
  <div class="card__image">
    <img src="data:image/jpeg;base64,{{recipe.image}}" alt="image">'
  </div>
  <div class="card__body body-card">
    <div class="body-card__text">
      <div class="body-card__title">
        <a href="{{ url_for('main.recipe', id=recipe.id) }}" class="body-card__link">{{ recipe.dish_name }}</a>
      </div>
      <div class="body-card__time">{{ recipe.cooking_time }}</div>
    </div>
    <div class="body-card__icons">
      <div class="body-card__rating"></div>
      <div class="body-card__buttons">
        <button class="body-card__like">
          <img src="{{ url_for('static', filename='images/all_recipe/like.svg') }}" alt="like">
        </button>
        <button class="body-card__comment">
          <img src="{{ url_for('static', filename='images/all_recipe/comments.svg') }}" alt="comments">
        </button>
      </div>
    </div>
  </div>
</div>
  {% endfor %}
</div>
</div>
{% endblock %}






